In [1]:
from pathlib import Path
import sys  
import os

import numpy as np
from operator import itemgetter

In [2]:
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..", "libs")))
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..", "src")))

In [24]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [19]:
# from libs.Recommenders.SLIM.SLIM_BPR_Python import SLIM_BPR_Python

In [6]:
from Utils.load_URM import load_URM
from Utils.load_ICM import load_ICM
from libs.Evaluation.Evaluator import EvaluatorHoldout
from Data_manager.split_functions.split_train_validation_random_holdout import split_train_in_two_percentage_global_sample

URM_all = load_URM("../data/data_train.csv")
ICM_all = load_ICM("../data/data_ICM_metadata.csv")

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1764607 stored elements and shape (35736, 38121)>

In [8]:
URM_train, URM_validation = split_train_in_two_percentage_global_sample(URM_all, train_percentage = 0.80)

In [9]:
evaluator_validation = EvaluatorHoldout(URM_validation, cutoff_list=[10])

EvaluatorHoldout: Ignoring 164 ( 0.5%) Users that have less than 1 test interactions


In [30]:
MAP_bpr = []

In [31]:
np.linspace(0.01, 0.25, 6)

array([0.01 , 0.058, 0.106, 0.154, 0.202, 0.25 ])

In [32]:
URM_train_coo = URM_train.tocoo()


for topK_ in [200, 300, 400]:
    for learning_rate_ in np.linspace(0.01, 0.25, 6):
        lambda_i_ = 0.0025
        lambda_j_ = 0.0025
        slim_bpr_model = SLIM_BPR_Python(URM_train_coo, verbose=False)
        slim_bpr_model.fit(learning_rate=learning_rate_,
                           lambda_i=lambda_i_,
                           lambda_j=lambda_j_,
                           topK = topK_,
                           epochs=100,
                          )

        result_dict, _ = evaluator_validation.evaluateRecommender(slim_bpr_model)
        MAP_bpr.append(('topK={}'.format(topK_),
                        'learning_rate={}'.format(learning_rate_),
                        'lambda_i_={}'.format(lambda_i_),
                        'lambda_j_={}'.format(lambda_j_),
                        result_dict["MAP"][10]))

        print(MAP_bpr[-1])
            

Train completed in 6.01 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 17.43 sec. Users per second: 2040
('topK=200', 'learning_rate=0.01', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.033031630893472066)
Train completed in 5.02 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 16.77 sec. Users per second: 2122
('topK=200', 'learning_rate=0.058', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.03493607706052789)
Train completed in 4.21 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 16.32 sec. Users per second: 2179
('topK=200', 'learning_rate=0.106', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.035693682434361156)
Train completed in 3.95 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 16.11 sec. Users per second: 2208
('topK=200', 'learning_rate=0.15400000000000003', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.03589884388678138)
Train completed in 3.81 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 16.06 sec. Users per second: 2215
('topK=200', 'learning_rate=0.202', '

/Users/safuan/Python/RecSysCompetition2024Polimi/libs/Recommenders/SLIM/SLIM_BPR_Python.py:78: RuntimeWarning: overflow encountered in exp
  sigmoid_gradient = 1 / (1 + np.exp(x_uij))


Train completed in 3.78 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 15.73 sec. Users per second: 2262
('topK=200', 'learning_rate=0.25', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.03612579124092149)
Train completed in 3.78 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 19.22 sec. Users per second: 1851
('topK=300', 'learning_rate=0.01', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.031885314470291436)
Train completed in 3.72 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 18.63 sec. Users per second: 1909
('topK=300', 'learning_rate=0.058', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.03399542303050975)
Train completed in 3.73 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 18.36 sec. Users per second: 1937
('topK=300', 'learning_rate=0.106', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.034322286306934305)
Train completed in 3.73 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 18.21 sec. Users per second: 1953
('topK=300', 'learning_rate=0.15400000000000003', 'l

/Users/safuan/Python/RecSysCompetition2024Polimi/libs/Recommenders/SLIM/SLIM_BPR_Python.py:78: RuntimeWarning: overflow encountered in exp
  sigmoid_gradient = 1 / (1 + np.exp(x_uij))


Train completed in 3.72 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 18.04 sec. Users per second: 1971
('topK=300', 'learning_rate=0.202', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.034456908831907884)


/Users/safuan/Python/RecSysCompetition2024Polimi/libs/Recommenders/SLIM/SLIM_BPR_Python.py:78: RuntimeWarning: overflow encountered in exp
  sigmoid_gradient = 1 / (1 + np.exp(x_uij))


Train completed in 3.73 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 18.04 sec. Users per second: 1972
('topK=300', 'learning_rate=0.25', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.034579695097786224)
Train completed in 3.74 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 20.98 sec. Users per second: 1696
('topK=400', 'learning_rate=0.01', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.031310013593455775)
Train completed in 3.75 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 20.40 sec. Users per second: 1743
('topK=400', 'learning_rate=0.058', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.0329619722382869)
Train completed in 3.75 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 20.15 sec. Users per second: 1765
('topK=400', 'learning_rate=0.106', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.03326204801533632)
Train completed in 3.72 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 20.09 sec. Users per second: 1771
('topK=400', 'learning_rate=0.15400000000000003', 'la

/Users/safuan/Python/RecSysCompetition2024Polimi/libs/Recommenders/SLIM/SLIM_BPR_Python.py:78: RuntimeWarning: overflow encountered in exp
  sigmoid_gradient = 1 / (1 + np.exp(x_uij))


Train completed in 3.75 minutes
EvaluatorHoldout: Processed 35568 (100.0%) in 19.87 sec. Users per second: 1790
('topK=400', 'learning_rate=0.25', 'lambda_i_=0.0025', 'lambda_j_=0.0025', 0.03378841958885719)


In [36]:
max_tuple = max(MAP_bpr, key=itemgetter(3))
print('The best combination for the ICF recommender is ({},{},{}), with a MAP = {}'.format(max_tuple[0],max_tuple[1], max_tuple[2], max_tuple[3]))

The best combination for the ICF recommender is (topK=200,learning_rate=0.01,lambda_i_=0.0025), with a MAP = lambda_j_=0.0025


In [25]:
from libs.Recommenders.SLIM.SLIMElasticNetRecommender import SLIMElasticNetRecommender

In [19]:
MAP = []

In [16]:
np.linspace(0.0001, 0.0005, 4)

array([0.0001    , 0.00023333, 0.00036667, 0.0005    ])

In [20]:
URM_train_coo = URM_train.tocoo()


for topK_ in [600]:
    for l1_ratio_ in np.linspace(0.01, 0.4, 10):
        for alpha_ in np.linspace(0.0001, 0.0005, 4):
            slim_model = SLIMElasticNetRecommender(URM_train_coo, verbose=True)
            slim_model.fit(l1_ratio=l1_ratio_, alpha = alpha_, topK = topK_)

            result_dict, _ = evaluator_validation.evaluateRecommender(slim_model)
            MAP.append(('topK={}'.format(topK_), 'l1_ratio={}'.format(l1_ratio_), 'alpha={}'.format(alpha_), result_dict["MAP"][10]))

            print(MAP[-1])
            

SLIMElasticNetRecommender: Processed 7719 (20.2%) in 5.00 min. Items per second: 25.73
SLIMElasticNetRecommender: Processed 15522 (40.7%) in 10.00 min. Items per second: 25.87
SLIMElasticNetRecommender: Processed 23264 (61.0%) in 15.00 min. Items per second: 25.85
SLIMElasticNetRecommender: Processed 30875 (81.0%) in 20.00 min. Items per second: 25.73
SLIMElasticNetRecommender: Processed 38121 (100.0%) in 24.53 min. Items per second: 25.90
EvaluatorHoldout: Processed 35574 (100.0%) in 18.55 sec. Users per second: 1917
('topK=600', 'l1_ratio=0.01', 'alpha=0.0001', 0.05999584367394966)
SLIMElasticNetRecommender: Processed 8313 (21.8%) in 5.00 min. Items per second: 27.71
SLIMElasticNetRecommender: Processed 16374 (43.0%) in 10.00 min. Items per second: 27.29
SLIMElasticNetRecommender: Processed 24714 (64.8%) in 15.00 min. Items per second: 27.46
SLIMElasticNetRecommender: Processed 33101 (86.8%) in 20.00 min. Items per second: 27.58
SLIMElasticNetRecommender: Processed 38121 (100.0%) in 

In [21]:
max_tuple = max(MAP, key=itemgetter(3))
print('The best combination for the ICF recommender is ({},{},{}), with a MAP = {}'.format(max_tuple[0],max_tuple[1], max_tuple[2], max_tuple[3]))

The best combination for the ICF recommender is (topK=600,l1_ratio=0.09666666666666666,alpha=0.00023333333333333333), with a MAP = 0.0615896653164726


In [22]:
slim_model = SLIMElasticNetRecommender(URM_train_coo, verbose=True)
slim_model.fit(l1_ratio=0.112, alpha = 0.000255, topK = 600)

result_dict, _ = evaluator_validation.evaluateRecommender(slim_model)
MAP.append(('topK={}'.format(600), 'l1_ratio={}'.format(0.112), 'alpha={}'.format(0.000255), result_dict["MAP"][10]))

SLIMElasticNetRecommender: Processed 5051 (13.2%) in 11.20 min. Items per second: 7.52
SLIMElasticNetRecommender: Processed 5246 (13.8%) in 22.73 min. Items per second: 3.85
SLIMElasticNetRecommender: Processed 5449 (14.3%) in 37.88 min. Items per second: 2.40
SLIMElasticNetRecommender: Processed 6234 (16.4%) in 42.88 min. Items per second: 2.42
SLIMElasticNetRecommender: Processed 14486 (38.0%) in 47.88 min. Items per second: 5.04
SLIMElasticNetRecommender: Processed 22672 (59.5%) in 52.88 min. Items per second: 7.14
SLIMElasticNetRecommender: Processed 31114 (81.6%) in 57.88 min. Items per second: 8.96
SLIMElasticNetRecommender: Processed 38121 (100.0%) in 1.04 hour. Items per second: 10.21
EvaluatorHoldout: Processed 35574 (100.0%) in 14.80 sec. Users per second: 2404


0.061551970584900265

In [11]:
MAP = [] 

In [16]:
np.linspace(0.0001, 0.0005, 10)

array([0.0001    , 0.00014444, 0.00018889, 0.00023333, 0.00027778,
       0.00032222, 0.00036667, 0.00041111, 0.00045556, 0.0005    ])

In [17]:
URM_train_coo = URM_train.tocoo()


for topK_ in [300, 350]:
    for l1_ratio_ in np.linspace(0.1, 0.18, 10):
        for alpha_ in np.linspace(0.0001, 0.0005, 10):
            slim_model = SLIMElasticNetRecommender(URM_train_coo, verbose=True)
            slim_model.fit(l1_ratio=l1_ratio_, alpha = alpha_, topK = topK_)

            result_dict, _ = evaluator_validation.evaluateRecommender(slim_model)
            MAP.append(('topK={}'.format(topK_), 'l1_ratio={}'.format(l1_ratio_), 'alpha={}'.format(alpha_), result_dict["MAP"][10]))

            print(MAP[-1])
            

SLIMElasticNetRecommender: Processed 7966 (20.9%) in 5.00 min. Items per second: 26.55
SLIMElasticNetRecommender: Processed 15980 (41.9%) in 10.00 min. Items per second: 26.63
SLIMElasticNetRecommender: Processed 23985 (62.9%) in 15.00 min. Items per second: 26.65
SLIMElasticNetRecommender: Processed 31904 (83.7%) in 20.00 min. Items per second: 26.58
SLIMElasticNetRecommender: Processed 38121 (100.0%) in 23.83 min. Items per second: 26.66
EvaluatorHoldout: Processed 35572 (100.0%) in 15.71 sec. Users per second: 2264
('topK=300', 'l1_ratio=0.1', 'alpha=0.0001', 0.05938700337700752)
SLIMElasticNetRecommender: Processed 8152 (21.4%) in 5.00 min. Items per second: 27.17
SLIMElasticNetRecommender: Processed 16351 (42.9%) in 10.00 min. Items per second: 27.25
SLIMElasticNetRecommender: Processed 24756 (64.9%) in 15.00 min. Items per second: 27.50
SLIMElasticNetRecommender: Processed 33208 (87.1%) in 20.00 min. Items per second: 27.67
SLIMElasticNetRecommender: Processed 38121 (100.0%) in 2


KeyboardInterrupt



In [18]:
max_tuple = max(MAP, key=itemgetter(3))
print('The best combination for the SSLIM recommender is ({},{},{}), with a MAP = {}'.format(max_tuple[0],max_tuple[1], max_tuple[2], max_tuple[3]))

The best combination for the SSLIM recommender is (topK=300,l1_ratio=0.11777777777777779,alpha=0.00023333333333333333), with a MAP = 0.06063653149703787


In [26]:
URM_train_coo = URM_train.tocoo()
slim_model = SLIMElasticNetRecommender(URM_train_coo, verbose=True)
slim_model.fit(l1_ratio=0.112, alpha = 0.0005, topK = 300)

SLIMElasticNetRecommender: Processed 9564 (25.1%) in 5.00 min. Items per second: 31.87
SLIMElasticNetRecommender: Processed 19069 (50.0%) in 10.00 min. Items per second: 31.78
SLIMElasticNetRecommender: Processed 28935 (75.9%) in 15.00 min. Items per second: 32.15
SLIMElasticNetRecommender: Processed 38121 (100.0%) in 19.52 min. Items per second: 32.56


In [27]:
result_dict, _ = evaluator_validation.evaluateRecommender(slim_model)
MAP.append(('topK={}'.format(topK_), 'l1_ratio={}'.format(l1_ratio_), 'alpha={}'.format(alpha_), result_dict["MAP"][10]))

print(MAP[-1])

TypeError: super(type, obj): obj must be an instance or subtype of type